import { useState } from "react";

export default function Documents() {
  const [documentName, setDocumentName] = useState("");
  const [analysis, setAnalysis] = useState(null);

  function analyzeDocument() {
    if (!documentName.trim()) return;

    setAnalysis({
      pages: 12,
      words: 3421,
      language: "English",
      summary:
        "This document discusses the uploaded topic, highlights the major concepts, and provides useful insights generated by MeshOS.",

      keywords: [
        "Artificial Intelligence",
        "Machine Learning",
        "Automation",
        "Data Analysis",
        "Cloud Computing",
      ],
    });
  }

  return (
    <div className="min-h-screen bg-[#0b0b0d] p-8 text-white">
      <h1 className="text-4xl font-bold">📄 AI Document Analysis</h1>

      <p className="mt-3 text-zinc-400">Analyze any document using MeshOS.</p>

      <input
        type="text"
        value={documentName}
        onChange={(e) => setDocumentName(e.target.value)}
        placeholder="Enter document name..."
        className="mt-8 w-full rounded-2xl border border-zinc-700 bg-zinc-900 p-4 outline-none"
      />

      <button
        onClick={analyzeDocument}
        className="mt-5 rounded-xl bg-green-600 px-6 py-3 font-semibold hover:bg-green-500"
      >
        Analyze Document
      </button>

      {analysis && (
        <div className="mt-10 rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
          <h2 className="text-2xl font-semibold">Analysis Result</h2>

          <div className="mt-6 grid gap-4 md:grid-cols-3">
            <div className="rounded-xl bg-zinc-950 p-4">
              <p className="text-zinc-500">Pages</p>
              <h3 className="mt-2 text-2xl font-bold">{analysis.pages}</h3>
            </div>

            <div className="rounded-xl bg-zinc-950 p-4">
              <p className="text-zinc-500">Words</p>
              <h3 className="mt-2 text-2xl font-bold">{analysis.words}</h3>
            </div>

            <div className="rounded-xl bg-zinc-950 p-4">
              <p className="text-zinc-500">Language</p>
              <h3 className="mt-2 text-2xl font-bold">{analysis.language}</h3>
            </div>
          </div>

          <h3 className="mt-8 text-xl font-semibold">AI Summary</h3>

          <p className="mt-3 text-zinc-300">{analysis.summary}</p>

          <h3 className="mt-8 text-xl font-semibold">Keywords</h3>

          <div className="mt-4 flex flex-wrap gap-3">
            {analysis.keywords.map((item, index) => (
              <span
                key={index}
                className="rounded-full bg-green-500/20 px-4 py-2 text-green-300"
              >
                {item}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
